// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrY9WAoPdA_OMUr7lqiSFN2_Dy_KnOAlY',
    appId: '1:85876900118:web:ef4477a362b501c8215037',
    messagingSenderId: '85876900118',
    projectId: 'taskapp-6e8f4',
    authDomain: 'taskapp-6e8f4.firebaseapp.com',
    storageBucket: 'taskapp-6e8f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXqwsCjjFUSYVDAoZhv-fSzZ_11XW3sOg',
    appId: '1:85876900118:android:3a678c84be14f390215037',
    messagingSenderId: '85876900118',
    projectId: 'taskapp-6e8f4',
    storageBucket: 'taskapp-6e8f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsu4Ib9uVZnTg6eYZcS6MX-h1JlcyVOTU',
    appId: '1:85876900118:ios:ffd064aa5e63c9de215037',
    messagingSenderId: '85876900118',
    projectId: 'taskapp-6e8f4',
    storageBucket: 'taskapp-6e8f4.firebasestorage.app',
    iosBundleId: 'com.example.taskapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsu4Ib9uVZnTg6eYZcS6MX-h1JlcyVOTU',
    appId: '1:85876900118:ios:ffd064aa5e63c9de215037',
    messagingSenderId: '85876900118',
    projectId: 'taskapp-6e8f4',
    storageBucket: 'taskapp-6e8f4.firebasestorage.app',
    iosBundleId: 'com.example.taskapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrY9WAoPdA_OMUr7lqiSFN2_Dy_KnOAlY',
    appId: '1:85876900118:web:31c2730512e52194215037',
    messagingSenderId: '85876900118',
    projectId: 'taskapp-6e8f4',
    authDomain: 'taskapp-6e8f4.firebaseapp.com',
    storageBucket: 'taskapp-6e8f4.firebasestorage.app',
  );

}